#ifndef ICL_FFI_H
#define ICL_FFI_H

/* This file is auto-generated by cbindgen. Do not edit. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

/**
 * Result from an ICL FFI call.
 * If `error` is null, the call succeeded and `result` contains the output.
 * If `error` is non-null, the call failed and `error` contains the error message.
 * The caller MUST free both `result` and `error` with `icl_free_string()`.
 */
typedef struct IclResult {
  char *result;
  char *error;
} IclResult;

/**
 * Parse ICL contract text and return a JSON string of the parsed Contract.
 *
 * # Safety
 * `text` must be a valid null-terminated UTF-8 C string.
 * The caller must free the returned strings with `icl_free_string()`.
 */
struct IclResult icl_parse_contract(const char *text);

/**
 * Normalize ICL contract text to canonical form.
 *
 * # Safety
 * `text` must be a valid null-terminated UTF-8 C string.
 * The caller must free the returned strings with `icl_free_string()`.
 */
struct IclResult icl_normalize(const char *text);

/**
 * Verify an ICL contract for correctness.
 * Returns JSON: { "valid": bool, "errors": [...], "warnings": [...] }
 *
 * # Safety
 * `text` must be a valid null-terminated UTF-8 C string.
 * The caller must free the returned strings with `icl_free_string()`.
 */
struct IclResult icl_verify(const char *text);

/**
 * Execute an ICL contract with the given inputs.
 *
 * # Safety
 * `text` and `inputs` must be valid null-terminated UTF-8 C strings.
 * The caller must free the returned strings with `icl_free_string()`.
 */
struct IclResult icl_execute(const char *text, const char *inputs);

/**
 * Compute the SHA-256 semantic hash of a contract.
 *
 * # Safety
 * `text` must be a valid null-terminated UTF-8 C string.
 * The caller must free the returned strings with `icl_free_string()`.
 */
struct IclResult icl_semantic_hash(const char *text);

/**
 * Free a string previously returned by an ICL FFI function.
 *
 * # Safety
 * `ptr` must be a pointer previously returned by an ICL FFI function,
 * or null (in which case this is a no-op).
 */
void icl_free_string(char *ptr);

#endif  /* ICL_FFI_H */
